### ISSUE TITLE
Where is the chromosomer executable located?

### ISSUE THREAD

**Issue by davidjstudholme** [gtamazian/chromosomer#20]
I apologise in advance if I am doing something stupid, but ... when I use pip to install chromosomer, it appears to go well; but then I cannot find the 'chromosomer' executable:

$ **pip install chromosomer**

Collecting chromosomer
  Downloading chromosomer-0.1.3-py2-none-any.whl
Collecting pyfaidx (from chromosomer)
  Downloading pyfaidx-0.5.3.1.tar.gz
Collecting future (from chromosomer)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 1.6MB/s 
Collecting bioformats (from chromosomer)
  Downloading bioformats-0.1.15-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 10.1MB/s 
Collecting six (from pyfaidx->chromosomer)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting setuptools>=0.7 (from pyfaidx->chromosomer)
  Downloading setuptools-39.0.0-py2.py3-none-any.whl (569kB)
    100% |████████████████████████████████| 573kB 2.1MB/s 
Collecting pyvcf (from bioformats->chromosomer)
  Downloading PyVCF-0.6.8.tar.gz
Building wheels for collected packages: pyfaidx, future, pyvcf
  Running setup.py bdist_wheel for pyfaidx ... done
  Stored in directory: /home/djs217/.cache/pip/wheels/5f/09/c4/72eca765669b7fdafd0e82128a1d30d5ae342e60fddc4d8fc3
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /home/djs217/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
  Running setup.py bdist_wheel for pyvcf ... done
  Stored in directory: /home/djs217/.cache/pip/wheels/4c/cb/3a/76a743f5fb96613d53bb60ce20e67546af54610a85e1a0fa17
Successfully built pyfaidx future pyvcf
Installing collected packages: six, setuptools, pyfaidx, future, pyvcf, bioformats, chromosomer
Successfully installed bioformats-0.1.15 chromosomer-0.1.3 future-0.16.0 pyfaidx-0.5.3.1 pyvcf-0.6.8 setuptools-39.0.0 six-1.11.0

$ **pip2 install chromosomer**

Collecting chromosomer
  Using cached chromosomer-0.1.3-py2-none-any.whl
Collecting pyfaidx (from chromosomer)
Collecting future (from chromosomer)
Collecting bioformats (from chromosomer)
  Using cached bioformats-0.1.15-py2.py3-none-any.whl
Collecting setuptools>=0.7 (from pyfaidx->chromosomer)
  Using cached setuptools-39.0.0-py2.py3-none-any.whl
Collecting six (from pyfaidx->chromosomer)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting pyvcf (from bioformats->chromosomer)
Installing collected packages: setuptools, six, pyfaidx, future, pyvcf, bioformats, chromosomer
Successfully installed bioformats-0.1.15 chromosomer-0.1.3 future-0.15.2 pyfaidx-0.5.3.1 pyvcf-0.6.8 setuptools-20.7.0 six-1.10.0

$ **chromosomer**
chromosomer: command not found

$ **pip --version**
pip 9.0.2 from /home/djs217/.local/lib/python2.7/site-packages (python 2.7)

$ **pip2 --version**
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

Really keen to try out your software on my _Xanthomonas_ genomes!
Best wishes,
David

**Comment by gtamazian** [comment]
Hello David,

It looks like you have two Python instances installed. You may check directories `/usr/local/bin` and `/home/djs217/.local/bin` for the **chromosomer** executable.

Another (and more robust) option is to establish a separate virtual environment and install Chromosomer to it. For that purpose, I would advise to use [the **virtualenvwrapper** package](http://virtualenvwrapper.readthedocs.io/).

Best regards,
Gaik

**Comment by davidjstudholme** [comment]
Thanks very much for the prompt and helpful response. Yes, I found the executable in the location that you suggested. I will also consider using the virtualenvwrapper package.
