### ISSUE TITLE
installation problem - bioformats

### ISSUE THREAD

**Issue by tk2** [gtamazian/chromosomer#9]
Hi - I'm having issues with getting the bioformats package, when I run chromosomer I get:

pkg_resources.DistributionNotFound: bioformats

but do have python-bioformats installed:
pip install python-bioformats
Requirement already satisfied (use --upgrade to upgrade): python-bioformats in XXXX
Requirement already satisfied (use --upgrade to upgrade): javabridge>=1.0 in XXXX
Requirement already satisfied (use --upgrade to upgrade): numpy in XXXX
Cleaning up...

Any ideas?
Thomas

**Comment by gtamazian** [comment]
Hi Tomas,

[python-bioformats](https://pypi.python.org/pypi/python-bioformats) and [bioformats](https://pypi.python.org/pypi/bioformats) are different packages. Please try to install the bioformats package in the following way:

```
pip install bioformats
```

Gaik

**Comment by tk2** [comment]
Thanks. When I run 'pip install bioformats', I'm getting:

Downloading/unpacking bioformats
   Could not find any downloads that satisfy the requirement bioformats
No distributions at all found for bioformats

Thomas

On 09/05/16 16:46, Gaik Tamazian wrote:
>
> Hi Tomas,
>
> python-bioformats <https://pypi.python.org/pypi/python-bioformats> and 
> bioformats <https://pypi.python.org/pypi/bioformats> are different 
> packages. Please try to install the bioformats package in the 
> following way:
>
> |pip install bioformats |
>
> Gaik
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gtamazian/chromosomer/issues/9#issuecomment-217903558>
>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gtamazian** [comment]
Could you please show the output of the following commands?
```
pip -V
```
and 
```
python -V
```

**Comment by tk2** [comment]
My pip version (pip --version) is 1.1. And python version is 2.7.3 
(python -V). Are these compatible?

Thomas

On 09/05/16 16:54, Gaik Tamazian wrote:
>
> Could you please show the output of the following commands?
>
> |pip -V |
>
> and
>
> |python -V |
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gtamazian/chromosomer/issues/9#issuecomment-217905817>
>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gtamazian** [comment]
The **Python** version seems fine but **pip** looks outdated. Please try to update it via the following command:
```
pip install --upgrade pip
```
I checked both **Chromosomer** and **bioformats** to work on **Python 2.7.11** and **pip 8.1.1**.

Gaik

**Comment by tk2** [comment]
Thanks, that worked.
Thomas

On 09/05/16 17:36, Gaik Tamazian wrote:
>
> The *Python* version seems fine but *pip* looks outdated. Please try 
> to update it via the following command:
>
> |pip install --upgrade pip |
>
> I checked both *Chromosomer* and *bioformats* to work on *Python 
> 2.7.11* and *pip 8.1.1*.
>
> Gaik
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gtamazian/chromosomer/issues/9#issuecomment-217917407>
>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
